################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/petr\ david/STM32CubeIDE/WBA_ZB_1_6_1/Zigbee_OnOff_Router_Demo/Utilities/trace/adv_trace/stm32_adv_trace.c \
C:/Users/petr\ david/STM32CubeIDE/WBA_ZB_1_6_1/Zigbee_OnOff_Router_Demo/Utilities/lpm/tiny_lpm/stm32_lpm.c \
C:/Users/petr\ david/STM32CubeIDE/WBA_ZB_1_6_1/Zigbee_OnOff_Router_Demo/Utilities/misc/stm32_mem.c \
C:/Users/petr\ david/STM32CubeIDE/WBA_ZB_1_6_1/Zigbee_OnOff_Router_Demo/Utilities/sequencer/stm32_seq.c \
C:/Users/petr\ david/STM32CubeIDE/WBA_ZB_1_6_1/Zigbee_OnOff_Router_Demo/Utilities/tim_serv/stm32_timer.c \
C:/Users/petr\ david/STM32CubeIDE/WBA_ZB_1_6_1/Zigbee_OnOff_Router_Demo/Utilities/misc/stm32_tiny_vsnprintf.c 

OBJS += \
./Utilities/stm32_adv_trace.o \
./Utilities/stm32_lpm.o \
./Utilities/stm32_mem.o \
./Utilities/stm32_seq.o \
./Utilities/stm32_timer.o \
./Utilities/stm32_tiny_vsnprintf.o 

C_DEPS += \
./Utilities/stm32_adv_trace.d \
./Utilities/stm32_lpm.d \
./Utilities/stm32_mem.d \
./Utilities/stm32_seq.d \
./Utilities/stm32_timer.d \
./Utilities/stm32_tiny_vsnprintf.d 


# Each subdirectory must supply rules for building sources it contributes
Utilities/stm32_adv_trace.o: C:/Users/petr\ david/STM32CubeIDE/WBA_ZB_1_6_1/Zigbee_OnOff_Router_Demo/Utilities/trace/adv_trace/stm32_adv_trace.c Utilities/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DSTM32 -DSTM32WBA -DSTM32WBA65xx -DSTM32WBA65RIx -DUSE_HAL_DRIVER -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DMAC -DMAC_LAYER -DAPPLICATION_USE_BAREMETAL -DAPPLICATION_USE_NUCLEO -DAPPLICATION_USE_HW_AES -DAPPLICATION_USE_HW_RNG -DAPPLICATION_USE_AMM -DAPPLICATION_USE_SMPS -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../System/Config/CRC_Ctrl -I../../System/Config/Debug_GPIO -I../../System/Config/Log -I../../System/Config/LowPower -I../../System/Interfaces -I../../Projects/Common/WPAN/Interfaces -I../../Projects/Common/WPAN/Modules -I../../Projects/Common/WPAN/Modules/BasicAES -I../../Projects/Common/WPAN/Modules/Flash -I../../Projects/Common/WPAN/Modules/Log -I../../Projects/Common/WPAN/Modules/MemoryManager -I../../Projects/Common/WPAN/Modules/RTDebug -I../../Projects/Common/WPAN/Modules/SerialCmdInterpreter -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/Device/ST/STM32WBAxx/Include -I../../Drivers/STM32WBAxx_HAL_Driver/Inc -I../../Drivers/BSP/Components/Common -I../../Drivers/BSP/STM32WBAxx_Nucleo -I../../Middlewares/ST/STM32_WPAN -I../../Middlewares/ST/STM32_WPAN/zigbee/include -I../../Middlewares/ST/STM32_WPAN/zigbee/stack/include -I../../Middlewares/ST/STM32_WPAN/zigbee/stack/port/stm32wba -I../../Middlewares/ST/STM32_WPAN/zigbee/stack/port/mac -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_sys/inc -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/config/ieee_15_4_basic -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/inc -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/inc/ot_inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Middlewares/ST/STM32_WPAN/interface -I../../Utilities/conf -I../../Utilities/lpm/tiny_lpm -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/tim_serv -I../../Utilities/trace/adv_trace -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Utilities/stm32_adv_trace.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Utilities/stm32_lpm.o: C:/Users/petr\ david/STM32CubeIDE/WBA_ZB_1_6_1/Zigbee_OnOff_Router_Demo/Utilities/lpm/tiny_lpm/stm32_lpm.c Utilities/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DSTM32 -DSTM32WBA -DSTM32WBA65xx -DSTM32WBA65RIx -DUSE_HAL_DRIVER -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DMAC -DMAC_LAYER -DAPPLICATION_USE_BAREMETAL -DAPPLICATION_USE_NUCLEO -DAPPLICATION_USE_HW_AES -DAPPLICATION_USE_HW_RNG -DAPPLICATION_USE_AMM -DAPPLICATION_USE_SMPS -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../System/Config/CRC_Ctrl -I../../System/Config/Debug_GPIO -I../../System/Config/Log -I../../System/Config/LowPower -I../../System/Interfaces -I../../Projects/Common/WPAN/Interfaces -I../../Projects/Common/WPAN/Modules -I../../Projects/Common/WPAN/Modules/BasicAES -I../../Projects/Common/WPAN/Modules/Flash -I../../Projects/Common/WPAN/Modules/Log -I../../Projects/Common/WPAN/Modules/MemoryManager -I../../Projects/Common/WPAN/Modules/RTDebug -I../../Projects/Common/WPAN/Modules/SerialCmdInterpreter -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/Device/ST/STM32WBAxx/Include -I../../Drivers/STM32WBAxx_HAL_Driver/Inc -I../../Drivers/BSP/Components/Common -I../../Drivers/BSP/STM32WBAxx_Nucleo -I../../Middlewares/ST/STM32_WPAN -I../../Middlewares/ST/STM32_WPAN/zigbee/include -I../../Middlewares/ST/STM32_WPAN/zigbee/stack/include -I../../Middlewares/ST/STM32_WPAN/zigbee/stack/port/stm32wba -I../../Middlewares/ST/STM32_WPAN/zigbee/stack/port/mac -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_sys/inc -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/config/ieee_15_4_basic -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/inc -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/inc/ot_inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Middlewares/ST/STM32_WPAN/interface -I../../Utilities/conf -I../../Utilities/lpm/tiny_lpm -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/tim_serv -I../../Utilities/trace/adv_trace -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Utilities/stm32_lpm.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Utilities/stm32_mem.o: C:/Users/petr\ david/STM32CubeIDE/WBA_ZB_1_6_1/Zigbee_OnOff_Router_Demo/Utilities/misc/stm32_mem.c Utilities/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DSTM32 -DSTM32WBA -DSTM32WBA65xx -DSTM32WBA65RIx -DUSE_HAL_DRIVER -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DMAC -DMAC_LAYER -DAPPLICATION_USE_BAREMETAL -DAPPLICATION_USE_NUCLEO -DAPPLICATION_USE_HW_AES -DAPPLICATION_USE_HW_RNG -DAPPLICATION_USE_AMM -DAPPLICATION_USE_SMPS -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../System/Config/CRC_Ctrl -I../../System/Config/Debug_GPIO -I../../System/Config/Log -I../../System/Config/LowPower -I../../System/Interfaces -I../../Projects/Common/WPAN/Interfaces -I../../Projects/Common/WPAN/Modules -I../../Projects/Common/WPAN/Modules/BasicAES -I../../Projects/Common/WPAN/Modules/Flash -I../../Projects/Common/WPAN/Modules/Log -I../../Projects/Common/WPAN/Modules/MemoryManager -I../../Projects/Common/WPAN/Modules/RTDebug -I../../Projects/Common/WPAN/Modules/SerialCmdInterpreter -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/Device/ST/STM32WBAxx/Include -I../../Drivers/STM32WBAxx_HAL_Driver/Inc -I../../Drivers/BSP/Components/Common -I../../Drivers/BSP/STM32WBAxx_Nucleo -I../../Middlewares/ST/STM32_WPAN -I../../Middlewares/ST/STM32_WPAN/zigbee/include -I../../Middlewares/ST/STM32_WPAN/zigbee/stack/include -I../../Middlewares/ST/STM32_WPAN/zigbee/stack/port/stm32wba -I../../Middlewares/ST/STM32_WPAN/zigbee/stack/port/mac -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_sys/inc -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/config/ieee_15_4_basic -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/inc -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/inc/ot_inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Middlewares/ST/STM32_WPAN/interface -I../../Utilities/conf -I../../Utilities/lpm/tiny_lpm -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/tim_serv -I../../Utilities/trace/adv_trace -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Utilities/stm32_mem.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Utilities/stm32_seq.o: C:/Users/petr\ david/STM32CubeIDE/WBA_ZB_1_6_1/Zigbee_OnOff_Router_Demo/Utilities/sequencer/stm32_seq.c Utilities/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DSTM32 -DSTM32WBA -DSTM32WBA65xx -DSTM32WBA65RIx -DUSE_HAL_DRIVER -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DMAC -DMAC_LAYER -DAPPLICATION_USE_BAREMETAL -DAPPLICATION_USE_NUCLEO -DAPPLICATION_USE_HW_AES -DAPPLICATION_USE_HW_RNG -DAPPLICATION_USE_AMM -DAPPLICATION_USE_SMPS -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../System/Config/CRC_Ctrl -I../../System/Config/Debug_GPIO -I../../System/Config/Log -I../../System/Config/LowPower -I../../System/Interfaces -I../../Projects/Common/WPAN/Interfaces -I../../Projects/Common/WPAN/Modules -I../../Projects/Common/WPAN/Modules/BasicAES -I../../Projects/Common/WPAN/Modules/Flash -I../../Projects/Common/WPAN/Modules/Log -I../../Projects/Common/WPAN/Modules/MemoryManager -I../../Projects/Common/WPAN/Modules/RTDebug -I../../Projects/Common/WPAN/Modules/SerialCmdInterpreter -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/Device/ST/STM32WBAxx/Include -I../../Drivers/STM32WBAxx_HAL_Driver/Inc -I../../Drivers/BSP/Components/Common -I../../Drivers/BSP/STM32WBAxx_Nucleo -I../../Middlewares/ST/STM32_WPAN -I../../Middlewares/ST/STM32_WPAN/zigbee/include -I../../Middlewares/ST/STM32_WPAN/zigbee/stack/include -I../../Middlewares/ST/STM32_WPAN/zigbee/stack/port/stm32wba -I../../Middlewares/ST/STM32_WPAN/zigbee/stack/port/mac -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_sys/inc -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/config/ieee_15_4_basic -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/inc -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/inc/ot_inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Middlewares/ST/STM32_WPAN/interface -I../../Utilities/conf -I../../Utilities/lpm/tiny_lpm -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/tim_serv -I../../Utilities/trace/adv_trace -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Utilities/stm32_seq.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Utilities/stm32_timer.o: C:/Users/petr\ david/STM32CubeIDE/WBA_ZB_1_6_1/Zigbee_OnOff_Router_Demo/Utilities/tim_serv/stm32_timer.c Utilities/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DSTM32 -DSTM32WBA -DSTM32WBA65xx -DSTM32WBA65RIx -DUSE_HAL_DRIVER -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DMAC -DMAC_LAYER -DAPPLICATION_USE_BAREMETAL -DAPPLICATION_USE_NUCLEO -DAPPLICATION_USE_HW_AES -DAPPLICATION_USE_HW_RNG -DAPPLICATION_USE_AMM -DAPPLICATION_USE_SMPS -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../System/Config/CRC_Ctrl -I../../System/Config/Debug_GPIO -I../../System/Config/Log -I../../System/Config/LowPower -I../../System/Interfaces -I../../Projects/Common/WPAN/Interfaces -I../../Projects/Common/WPAN/Modules -I../../Projects/Common/WPAN/Modules/BasicAES -I../../Projects/Common/WPAN/Modules/Flash -I../../Projects/Common/WPAN/Modules/Log -I../../Projects/Common/WPAN/Modules/MemoryManager -I../../Projects/Common/WPAN/Modules/RTDebug -I../../Projects/Common/WPAN/Modules/SerialCmdInterpreter -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/Device/ST/STM32WBAxx/Include -I../../Drivers/STM32WBAxx_HAL_Driver/Inc -I../../Drivers/BSP/Components/Common -I../../Drivers/BSP/STM32WBAxx_Nucleo -I../../Middlewares/ST/STM32_WPAN -I../../Middlewares/ST/STM32_WPAN/zigbee/include -I../../Middlewares/ST/STM32_WPAN/zigbee/stack/include -I../../Middlewares/ST/STM32_WPAN/zigbee/stack/port/stm32wba -I../../Middlewares/ST/STM32_WPAN/zigbee/stack/port/mac -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_sys/inc -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/config/ieee_15_4_basic -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/inc -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/inc/ot_inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Middlewares/ST/STM32_WPAN/interface -I../../Utilities/conf -I../../Utilities/lpm/tiny_lpm -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/tim_serv -I../../Utilities/trace/adv_trace -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Utilities/stm32_timer.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Utilities/stm32_tiny_vsnprintf.o: C:/Users/petr\ david/STM32CubeIDE/WBA_ZB_1_6_1/Zigbee_OnOff_Router_Demo/Utilities/misc/stm32_tiny_vsnprintf.c Utilities/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DSTM32 -DSTM32WBA -DSTM32WBA65xx -DSTM32WBA65RIx -DUSE_HAL_DRIVER -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DMAC -DMAC_LAYER -DAPPLICATION_USE_BAREMETAL -DAPPLICATION_USE_NUCLEO -DAPPLICATION_USE_HW_AES -DAPPLICATION_USE_HW_RNG -DAPPLICATION_USE_AMM -DAPPLICATION_USE_SMPS -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../System/Config/CRC_Ctrl -I../../System/Config/Debug_GPIO -I../../System/Config/Log -I../../System/Config/LowPower -I../../System/Interfaces -I../../Projects/Common/WPAN/Interfaces -I../../Projects/Common/WPAN/Modules -I../../Projects/Common/WPAN/Modules/BasicAES -I../../Projects/Common/WPAN/Modules/Flash -I../../Projects/Common/WPAN/Modules/Log -I../../Projects/Common/WPAN/Modules/MemoryManager -I../../Projects/Common/WPAN/Modules/RTDebug -I../../Projects/Common/WPAN/Modules/SerialCmdInterpreter -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/Device/ST/STM32WBAxx/Include -I../../Drivers/STM32WBAxx_HAL_Driver/Inc -I../../Drivers/BSP/Components/Common -I../../Drivers/BSP/STM32WBAxx_Nucleo -I../../Middlewares/ST/STM32_WPAN -I../../Middlewares/ST/STM32_WPAN/zigbee/include -I../../Middlewares/ST/STM32_WPAN/zigbee/stack/include -I../../Middlewares/ST/STM32_WPAN/zigbee/stack/port/stm32wba -I../../Middlewares/ST/STM32_WPAN/zigbee/stack/port/mac -I../../Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_sys/inc -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/config/ieee_15_4_basic -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/inc -I../../Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/inc/ot_inc -I../../Middlewares/ST/STM32_WPAN/utilities -I../../Middlewares/ST/STM32_WPAN/interface -I../../Utilities/conf -I../../Utilities/lpm/tiny_lpm -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/tim_serv -I../../Utilities/trace/adv_trace -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Utilities/stm32_tiny_vsnprintf.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Utilities

clean-Utilities:
	-$(RM) ./Utilities/stm32_adv_trace.cyclo ./Utilities/stm32_adv_trace.d ./Utilities/stm32_adv_trace.o ./Utilities/stm32_adv_trace.su ./Utilities/stm32_lpm.cyclo ./Utilities/stm32_lpm.d ./Utilities/stm32_lpm.o ./Utilities/stm32_lpm.su ./Utilities/stm32_mem.cyclo ./Utilities/stm32_mem.d ./Utilities/stm32_mem.o ./Utilities/stm32_mem.su ./Utilities/stm32_seq.cyclo ./Utilities/stm32_seq.d ./Utilities/stm32_seq.o ./Utilities/stm32_seq.su ./Utilities/stm32_timer.cyclo ./Utilities/stm32_timer.d ./Utilities/stm32_timer.o ./Utilities/stm32_timer.su ./Utilities/stm32_tiny_vsnprintf.cyclo ./Utilities/stm32_tiny_vsnprintf.d ./Utilities/stm32_tiny_vsnprintf.o ./Utilities/stm32_tiny_vsnprintf.su

.PHONY: clean-Utilities

